### ISSUE TITLE
No Signal on Monitor, but HDD activity happening

### ISSUE THREAD

**Issue by Ironfist69** [QaidVoid/Complete-Single-GPU-Passthrough#11]
I’ve created a windows VM but not getting any display output from it (Using HDMI to VGA converter)
After starting the VM my screen goes black nothing happens but I’ve noticed my HDD LED indicator is blinking, that means windows is loading. Then I tried pressing blindly ALT+F4 & it shut down perfectly fine & goes back to Manjaro login screen. Even I dump my own GPU rom from GPU-z and patched it.

I’m trying this for almost one month. I don’t know what I’m doing wrong, I’ll provide any log outputs if you ask.

Specifications:
intel core i3-9100F
MSI H310M PRO VDH PLUS
16GB RAM
NVIDIA GTX 1650 4GB GDDR6

**Comment by TypicalGamer07** [comment]
**### Here is my win10.log**



2021-12-29 14:45:04.219+0000: starting up libvirt version: 7.10.0, qemu version: 6.1.0, kernel: 5.15.7-1-MANJARO, hostname: subha-ms7c09
LC_ALL=C
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin
HOME=/var/lib/libvirt/qemu/domain-1-win10
XDG_DATA_HOME=/var/lib/libvirt/qemu/domain-1-win10/.local/share
XDG_CACHE_HOME=/var/lib/libvirt/qemu/domain-1-win10/.cache
XDG_CONFIG_HOME=/var/lib/libvirt/qemu/domain-1-win10/.config
/usr/bin/qemu-system-x86_64
-name guest=win10,debug-threads=on
-S
-object '{"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-1-win10/master-key.aes"}'
-blockdev '{"driver":"file","filename":"/usr/share/edk2-ovmf/x64/OVMF_CODE.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-pflash0-format","read-only":true,"driver":"raw","file":"libvirt-pflash0-storage"}'
-blockdev '{"driver":"file","filename":"/var/lib/libvirt/qemu/nvram/win10_VARS.fd","node-name":"libvirt-pflash1-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-pflash1-format","read-only":false,"driver":"raw","file":"libvirt-pflash1-storage"}'
-machine pc-q35-6.1,usb=off,vmport=off,dump-guest-core=off,pflash0=libvirt-pflash0-format,pflash1=libvirt-pflash1-format,memory-backend=pc.ram
-accel kvm
-cpu host,migratable=on,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff
-m 8192
-object '{"qom-type":"memory-backend-ram","id":"pc.ram","size":8589934592}'
-overcommit mem-lock=off
-smp 2,sockets=1,dies=1,cores=2,threads=1
-uuid 569940cb-4a37-4b40-a533-2627cd3243f3
-no-user-config
-nodefaults
-chardev socket,id=charmonitor,fd=32,server=on,wait=off
-mon chardev=charmonitor,id=monitor,mode=control
-rtc base=localtime,driftfix=slew
-global kvm-pit.lost_tick_policy=delay
-no-hpet
-no-shutdown
-global ICH9-LPC.disable_s3=1
-global ICH9-LPC.disable_s4=1
-boot strict=on
-device pcie-root-port,port=16,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2
-device pcie-root-port,port=17,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1
-device pcie-root-port,port=18,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2
-device pcie-root-port,port=19,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x3
-device pcie-root-port,port=20,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x4
-device pcie-root-port,port=21,chassis=6,id=pci.6,bus=pcie.0,addr=0x2.0x5
-device qemu-xhci,p2=15,p3=15,id=usb,bus=pci.2,addr=0x0
-device virtio-serial-pci,id=virtio-serial0,bus=pci.3,addr=0x0
-blockdev '{"driver":"file","filename":"/var/lib/libvirt/images/win10.qcow2","node-name":"libvirt-3-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-3-format","read-only":false,"driver":"qcow2","file":"libvirt-3-storage","backing":null}'
-device virtio-blk-pci,bus=pci.4,addr=0x0,drive=libvirt-3-format,id=virtio-disk0,bootindex=2
-blockdev '{"driver":"file","filename":"/run/media/subha/Ventoy/17763.107.101029-1455.rs5_release_svc_refresh_CLIENT_LTSC_EVAL_x64FRE_en-us.iso","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-2-format","read-only":true,"driver":"raw","file":"libvirt-2-storage"}'
-device ide-cd,bus=ide.1,drive=libvirt-2-format,id=sata0-0-1,bootindex=1
-blockdev '{"driver":"file","filename":"/home/subha/Downloads/virtio-win-0.1.208.iso","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-1-format","read-only":true,"driver":"raw","file":"libvirt-1-storage"}'
-device ide-cd,bus=ide.2,drive=libvirt-1-format,id=sata0-0-2
-netdev tap,fd=34,id=hostnet0,vhost=on,vhostfd=36
-device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:67:6a:cc,bus=pci.1,addr=0x0
-chardev pty,id=charserial0
-device isa-serial,chardev=charserial0,id=serial0
-chardev spicevmc,id=charchannel0,name=vdagent
-device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0
-device usb-tablet,id=input0,bus=usb.0,port=1
-audiodev '{"id":"audio1","driver":"spice"}'
-spice port=5900,addr=127.0.0.1,disable-ticketing=on,image-compression=off,seamless-migration=on
-device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pcie.0,addr=0x1
-device ich9-intel-hda,id=sound0,bus=pcie.0,addr=0x1b
-device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0,audiodev=audio1
-chardev spicevmc,id=charredir0,name=usbredir
-device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=2
-chardev spicevmc,id=charredir1,name=usbredir
-device usb-redir,chardev=charredir1,id=redir1,bus=usb.0,port=3
-device virtio-balloon-pci,id=balloon0,bus=pci.5,addr=0x0
-sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny
-msg timestamp=on
char device redirected to /dev/pts/1 (label charserial0)
qxl_send_events: spice-server bug: guest stopped, ignoring
2021-12-29T14:51:47.757098Z qemu-system-x86_64: terminating on signal 15 from pid 2087 (/usr/bin/libvirtd)
2021-12-29 14:51:48.040+0000: shutting down, reason=shutdown
2021-12-29 14:51:48.455+0000: starting up libvirt version: 7.10.0, qemu version: 6.1.0, kernel: 5.15.7-1-MANJARO, hostname: subha-ms7c09
LC_ALL=C
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin
HOME=/var/lib/libvirt/qemu/domain-2-win10
XDG_DATA_HOME=/var/lib/libvirt/qemu/domain-2-win10/.local/share
XDG_CACHE_HOME=/var/lib/libvirt/qemu/domain-2-win10/.cache
XDG_CONFIG_HOME=/var/lib/libvirt/qemu/domain-2-win10/.config
/usr/bin/qemu-system-x86_64
-name guest=win10,debug-threads=on
-S
-object '{"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-2-win10/master-key.aes"}'
-blockdev '{"driver":"file","filename":"/usr/share/edk2-ovmf/x64/OVMF_CODE.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-pflash0-format","read-only":true,"driver":"raw","file":"libvirt-pflash0-storage"}'
-blockdev '{"driver":"file","filename":"/var/lib/libvirt/qemu/nvram/win10_VARS.fd","node-name":"libvirt-pflash1-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-pflash1-format","read-only":false,"driver":"raw","file":"libvirt-pflash1-storage"}'
-machine pc-q35-6.1,usb=off,vmport=off,dump-guest-core=off,pflash0=libvirt-pflash0-format,pflash1=libvirt-pflash1-format,memory-backend=pc.ram
-accel kvm
-cpu host,migratable=on,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff
-m 8192
-object '{"qom-type":"memory-backend-ram","id":"pc.ram","size":8589934592}'
-overcommit mem-lock=off
-smp 2,sockets=1,dies=1,cores=2,threads=1
-uuid 569940cb-4a37-4b40-a533-2627cd3243f3
-no-user-config
-nodefaults
-chardev socket,id=charmonitor,fd=32,server=on,wait=off
-mon chardev=charmonitor,id=monitor,mode=control
-rtc base=localtime,driftfix=slew
-global kvm-pit.lost_tick_policy=delay
-no-hpet
-no-shutdown
-global ICH9-LPC.disable_s3=1
-global ICH9-LPC.disable_s4=1
-boot strict=on
-device pcie-root-port,port=16,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2
-device pcie-root-port,port=17,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1
-device pcie-root-port,port=18,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2
-device pcie-root-port,port=19,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x3
-device pcie-root-port,port=20,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x4
-device pcie-root-port,port=21,chassis=6,id=pci.6,bus=pcie.0,addr=0x2.0x5
-device qemu-xhci,p2=15,p3=15,id=usb,bus=pci.2,addr=0x0
-device virtio-serial-pci,id=virtio-serial0,bus=pci.3,addr=0x0
-blockdev '{"driver":"file","filename":"/var/lib/libvirt/images/win10.qcow2","node-name":"libvirt-3-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-3-format","read-only":false,"driver":"qcow2","file":"libvirt-3-storage","backing":null}'
-device virtio-blk-pci,bus=pci.4,addr=0x0,drive=libvirt-3-format,id=virtio-disk0,bootindex=2
-blockdev '{"driver":"file","filename":"/run/media/subha/Ventoy/17763.107.101029-1455.rs5_release_svc_refresh_CLIENT_LTSC_EVAL_x64FRE_en-us.iso","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-2-format","read-only":true,"driver":"raw","file":"libvirt-2-storage"}'
-device ide-cd,bus=ide.1,drive=libvirt-2-format,id=sata0-0-1,bootindex=1
-blockdev '{"driver":"file","filename":"/home/subha/Downloads/virtio-win-0.1.208.iso","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-1-format","read-only":true,"driver":"raw","file":"libvirt-1-storage"}'
-device ide-cd,bus=ide.2,drive=libvirt-1-format,id=sata0-0-2
-netdev tap,fd=34,id=hostnet0,vhost=on,vhostfd=35
-device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:67:6a:cc,bus=pci.1,addr=0x0
-chardev pty,id=charserial0
-device isa-serial,chardev=charserial0,id=serial0
-chardev spicevmc,id=charchannel0,name=vdagent
-device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0
-device usb-tablet,id=input0,bus=usb.0,port=1
-audiodev '{"id":"audio1","driver":"spice"}'
-spice port=5900,addr=127.0.0.1,disable-ticketing=on,image-compression=off,seamless-migration=on
-device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pcie.0,addr=0x1
-device ich9-intel-hda,id=sound0,bus=pcie.0,addr=0x1b
-device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0,audiodev=audio1
-chardev spicevmc,id=charredir0,name=usbredir
-device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=2
-chardev spicevmc,id=charredir1,name=usbredir
-device usb-redir,chardev=charredir1,id=redir1,bus=usb.0,port=3
-device virtio-balloon-pci,id=balloon0,bus=pci.5,addr=0x0
-sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny
-msg timestamp=on
char device redirected to /dev/pts/1 (label charserial0)
qxl_send_events: spice-server bug: guest stopped, ignoring
2021-12-29T15:01:19.171409Z qemu-system-x86_64: terminating on signal 15 from pid 2087 (/usr/bin/libvirtd)
2021-12-29 15:01:19.440+0000: shutting down, reason=shutdown
2021-12-29 15:12:40.470+0000: starting up libvirt version: 7.10.0, qemu version: 6.1.0, kernel: 5.15.7-1-MANJARO, hostname: subha-ms7c09
LC_ALL=C
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin
HOME=/var/lib/libvirt/qemu/domain-1-win10
XDG_DATA_HOME=/var/lib/libvirt/qemu/domain-1-win10/.local/share
XDG_CACHE_HOME=/var/lib/libvirt/qemu/domain-1-win10/.cache
XDG_CONFIG_HOME=/var/lib/libvirt/qemu/domain-1-win10/.config
/usr/bin/qemu-system-x86_64
-name guest=win10,debug-threads=on
-S
-object '{"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-1-win10/master-key.aes"}'
-blockdev '{"driver":"file","filename":"/usr/share/edk2-ovmf/x64/OVMF_CODE.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-pflash0-format","read-only":true,"driver":"raw","file":"libvirt-pflash0-storage"}'
-blockdev '{"driver":"file","filename":"/var/lib/libvirt/qemu/nvram/win10_VARS.fd","node-name":"libvirt-pflash1-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-pflash1-format","read-only":false,"driver":"raw","file":"libvirt-pflash1-storage"}'
-machine pc-q35-6.1,usb=off,vmport=off,dump-guest-core=off,pflash0=libvirt-pflash0-format,pflash1=libvirt-pflash1-format,memory-backend=pc.ram
-accel kvm
-cpu host,migratable=on,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff,hv-vendor-id=6969,kvm=off
-m 8192
-object '{"qom-type":"memory-backend-ram","id":"pc.ram","size":8589934592}'
-overcommit mem-lock=off
-smp 2,sockets=1,dies=1,cores=2,threads=1
-uuid 569940cb-4a37-4b40-a533-2627cd3243f3
-display none
-no-user-config
-nodefaults
-chardev socket,id=charmonitor,fd=30,server=on,wait=off
-mon chardev=charmonitor,id=monitor,mode=control
-rtc base=localtime,driftfix=slew
-global kvm-pit.lost_tick_policy=delay
-no-hpet
-no-shutdown
-global ICH9-LPC.disable_s3=1
-global ICH9-LPC.disable_s4=1
-boot strict=on
-device pcie-root-port,port=16,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2
-device pcie-root-port,port=17,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1
-device pcie-root-port,port=18,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2
-device pcie-root-port,port=19,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x3
-device pcie-root-port,port=20,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x4
-device pcie-root-port,port=21,chassis=6,id=pci.6,bus=pcie.0,addr=0x2.0x5
-device pcie-root-port,port=8,chassis=7,id=pci.7,bus=pcie.0,multifunction=on,addr=0x1
-device pcie-root-port,port=9,chassis=8,id=pci.8,bus=pcie.0,addr=0x1.0x1
-device pcie-root-port,port=10,chassis=9,id=pci.9,bus=pcie.0,addr=0x1.0x2
-device qemu-xhci,p2=15,p3=15,id=usb,bus=pci.2,addr=0x0
-device virtio-serial-pci,id=virtio-serial0,bus=pci.3,addr=0x0
-blockdev '{"driver":"file","filename":"/var/lib/libvirt/images/win10.qcow2","node-name":"libvirt-3-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-3-format","read-only":false,"driver":"qcow2","file":"libvirt-3-storage","backing":null}'
-device virtio-blk-pci,bus=pci.4,addr=0x0,drive=libvirt-3-format,id=virtio-disk0,bootindex=2
-blockdev '{"driver":"file","filename":"/run/media/subha/Ventoy/17763.107.101029-1455.rs5_release_svc_refresh_CLIENT_LTSC_EVAL_x64FRE_en-us.iso","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-2-format","read-only":true,"driver":"raw","file":"libvirt-2-storage"}'
-device ide-cd,bus=ide.1,drive=libvirt-2-format,id=sata0-0-1,bootindex=1
-blockdev '{"driver":"file","filename":"/home/subha/Downloads/virtio-win-0.1.208.iso","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}'
-blockdev '{"node-name":"libvirt-1-format","read-only":true,"driver":"raw","file":"libvirt-1-storage"}'
-device ide-cd,bus=ide.2,drive=libvirt-1-format,id=sata0-0-2
-netdev tap,fd=33,id=hostnet0,vhost=on,vhostfd=34
-device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:67:6a:cc,bus=pci.1,addr=0x0
-chardev pty,id=charserial0
-device isa-serial,chardev=charserial0,id=serial0
-audiodev '{"id":"audio1","driver":"spice"}'
-chardev spicevmc,id=charredir0,name=usbredir
-device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=2
-chardev spicevmc,id=charredir1,name=usbredir
-device usb-redir,chardev=charredir1,id=redir1,bus=usb.0,port=3
-device usb-host,hostdevice=/dev/bus/usb/001/002,id=hostdev0,bus=usb.0,port=1
-device usb-host,hostdevice=/dev/bus/usb/001/003,id=hostdev1,bus=usb.0,port=4
-device vfio-pci,host=0000:01:00.0,id=hostdev2,bus=pci.6,addr=0x0,romfile=/usr/share/vgabios/TU116.rom
-device vfio-pci,host=0000:01:00.1,id=hostdev3,bus=pci.7,addr=0x0,romfile=/usr/share/vgabios/TU116.rom
-device vfio-pci,host=0000:01:00.2,id=hostdev4,bus=pci.8,addr=0x0,romfile=/usr/share/vgabios/TU116.rom
-device vfio-pci,host=0000:01:00.3,id=hostdev5,bus=pci.9,addr=0x0,romfile=/usr/share/vgabios/TU116.rom
-device virtio-balloon-pci,id=balloon0,bus=pci.5,addr=0x0
-sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny
-msg timestamp=on
char device redirected to /dev/pts/0 (label charserial0)
audio: Could not init `spice' audio driver
audio: warning: Using timer based audio emulation
2021-12-29T15:13:28.108034Z qemu-system-x86_64: terminating on signal 15 from pid 3717 (/usr/bin/libvirtd)
2021-12-29 15:13:31.085+0000: shutting down, reason=shutdown

**Comment by QaidVoid** [comment]
You only need to provide rom file to the GPU VGA PCI.
