### ISSUE TITLE
Nvidia Code 43

### ISSUE THREAD

**Issue by limendoza** [QaidVoid/Complete-Single-GPU-Passthrough#12]
I followed everything in the guide except I changed the Device Model from virtio to e1000e in NIC since I couldn't get the internet working. I encountered Code 43 any ideas how to resolve this? Thanks

**Comment by QaidVoid** [comment]
Did you set the `vendor_id` as mentioned in this section?
https://github.com/QaidVoid/Complete-Single-GPU-Passthrough#video-card-driver-virtualisation-detection

If you've already done that, then try solution mentioned here: https://www.reddit.com/r/VFIO/comments/othzvr/cant_fix_error_43_on_single_gpu_passthrough/

**Comment by limendoza** [comment]
I tried the solution given but I encountered 2 behaviors:

- video=vesafb:off vga=off
> Just stuck in a black screen.

-  video=vesafb:off,efifb:off vga=off
> This one works and the GPU passthrough works and code 43 issue is gone, however when I shutdown the machine it will be stuck on black screen.

**Comment by QaidVoid** [comment]
Add the following to the top of libvirt stop script, replacing username..
This will create the log file at `~/virsh_log`..
```sh
exec 19>/home/username/virsh_log
BASH_XTRACEFD=19
```
The log should show if anything is failing.

**Comment by limendoza** [comment]
Yeah I tried it. Below here is the content of the log.

`
+ modprobe -r vfio-pci
+ virsh nodedev-reattach pci_0000_07_00_0
+ virsh nodedev-reattach pci_0000_07_00_1
+ echo efi-framebuffer.0
+ modprobe nvidia_drm
+ modprobe nvidia_modeset
+ modprobe nvidia_uvm
+ modprobe nvidia
+ echo 1
+ echo 1
+ systemctl start display-manager
`
Hmm. I'm not sure what am I missing. Is there any other logs that I can check?
