### ISSUE TITLE
Poweroff after windows installer loading

### ISSUE THREAD

**Issue by K0SS4** [QaidVoid/Complete-Single-GPU-Passthrough#13]
So my problem begins right after creating the vm. I do everything as in the tutorial(https://github.com/QaidVoid/Complete-Single-GPU-Passthrough#setup-guest-os) and when i click "Begin installation" windows starts loading(spinning windows circle) and then it shuts down.
I tried starting it with virsh and then viewing with virt-viewer but it's the same.

VM log file: https://pastebin.com/uc7HBHr8
/etc/libvirt/qemu.conf(default for arch): https://pastebin.com/8C4HShzq
win11.xml: https://pastebin.com/8D430qUq

My groups: libvirt-qemu libvirt video kvm input audio wheel k0ss4

It doesn't matter if it's windows 10 or 11. It behaves the same on both.

Thanks in advance :)

**Comment by QaidVoid** [comment]
Couldn't find anything that might be causing the issue.

If your CPU has 16 threads only, try reducing the vCPU for VM.
Also, try setting the CPU topology manually.

**Comment by K0SS4** [comment]
Setting cpu topology manually didn't help. I set it to 1 socket, 4 cores, 2 threads and then 1 socket, 4 cores, 1 thread but it still crashes. However these lines in logs appear all the time:
``qxl_send_events: spice-server bug: guest stopped, ignoring``
``2022-05-16 06:19:39.337+0000: shutting down, reason=crashed``

But I don't know if it's spice-server causing the crash or if it simply cannot start because something else crashed before.

Thanks anyway

**Comment by K0SS4** [comment]
I solved it. It could not start because I gave it too much RAM. I don't have any swap partition/file so if firefox was launched on host then it crashed the vm bacuse i didn't have spare 15GB
