### ISSUE TITLE
KVM Not available.

### ISSUE THREAD

**Issue by EndLordMC** [QaidVoid/Complete-Single-GPU-Passthrough#19]
Linux/VM noob here. I'm trying to follow this guide to pass through my AMD card. However, after running `usermod -aG kvm,input,libvirt username` VM Manager tells me that KVM Isn't available. It was working just fine before i started messing around with this guide. I'm not %100 sure what the cause is.

I would post a log or something but i have no idea what to do in this situation, so any help would be greatly appreciated.

**Comment by QaidVoid** [comment]
That's odd. Which GPU driver have you installed? Also, could you please check if the kvm module is loaded using `lsmod | grep kvm`.

Also, you can probably check `dmesg` or `journalctl -f` to see if any related error message is logged..

**Comment by EndLordMC** [comment]
My GPU is an AMD R7 240, with oland radeon drivers.

`lsmod | grep kvm` outputs this:
```
kvm                  1105920  0
irqbypass              16384  1 kvm
```
No idea if that's good or bad.

`dmesg` reports that KVM is disabled by my bios, which would make sense, since i recently performed a bios update, in preparation for this guide. I do have SR-IOV enabled in my bios, which i assume is a good thing. I went through all my bios settings but didn't find anything. AMD CPU btw.

Here's more system info:
https://pastebin.com/rdjVMAnG

**Comment by QaidVoid** [comment]
Your system info shows that your CPU is missing the flag required for KVM.. The CPU should either have `vmx` or `svm' flag present for KVM..

SR-IOV is different than that what is required for KVM.. There should be something else related to virtualization in your BIOS settings.. It might be named `VT-d`, `VT-x` or `AMD-SVM`. Check again and make sure if any of them is present and enable it...

**Comment by EndLordMC** [comment]
As it turns out, i had SVM disabled, my bad lol. I should really look more closely next time.

Looks like my vm is working fine now. Thank you for your help!
