### ISSUE TITLE
Possible instructions for peripherals passthrough via GUI

### ISSUE THREAD

**Issue by binarydepth** [QaidVoid/Complete-Single-GPU-Passthrough#2]
`sudo virsh edit win10` doesn't let me type

**Comment by QaidVoid** [comment]
It uses vim as default editor.. If you are unfamiliar

**Comment by QaidVoid** [comment]
virsh uses vim as default editor.. If you're unfamiliar with vim, you can use other editor, such as nano using
sudo EDITOR=nano virsh edit win10
