### ISSUE TITLE
Black screen/system unresponsive

### ISSUE THREAD

**Issue by EndLordMC** [QaidVoid/Complete-Single-GPU-Passthrough#21]
Upon launching the VM, my GPU outputs no signal to the display, and my system appears to be completely frozen, forcing me to hard reboot.

System info: [output.txt](https://github.com/QaidVoid/Complete-Single-GPU-Passthrough/files/10371293/output.txt)

Guest Config: [win10.xml.txt](https://github.com/QaidVoid/Complete-Single-GPU-Passthrough/files/10371248/win10.xml.txt)

Libvirtd log: [log3.zip](https://github.com/QaidVoid/Complete-Single-GPU-Passthrough/files/10371085/log3.zip)

Start hook: [start.txt](https://github.com/QaidVoid/Complete-Single-GPU-Passthrough/files/10371279/start.txt)

Stop hook: [stop.txt](https://github.com/QaidVoid/Complete-Single-GPU-Passthrough/files/10371271/stop.txt)

One thing i noticed while quickly skimming over the Libvirtd log, is that at the end, there was a line that read `713: warning : virHookCheck:187 : Non-executable hook script /etc/libvirt/hooks/qemu.d/win10` which doesn't make sense to me, since i did everything i could to make sure they were executable.

I uploaded all the logs i could find relating to this, but for some reason there was no win10 log at `/var/log/libvirt/qemu/`, even though i know there was one there at some point. Anyway, i just want to be sure I'm covering all my bases, so please bear with me if i miss something, I'm still learning all this stuff.

As always, any help with this issue is much appreciated!

**Comment by EndLordMC** [comment]
Also could potentially relate to issues #3 and #8

**Comment by QaidVoid** [comment]
You forgot to set the firmware to `UEFI`. Everything else looks okay to me..

Not sure why'd it complain about the hook script being non-executable though..
