### ISSUE TITLE
vBIOS Patching 

### ISSUE THREAD

**Issue by 3ndlos** [QaidVoid/Complete-Single-GPU-Passthrough#23]
Hey there - really helpful guide, thank's a lot!

I still have a few little problems but here's a solution for one I had with creating the .rom:

I was unable to execute the given commands with a permission denied.
Even in live linux I got the permission denied error.

Simple solution:
`echo 1 | sudo tee /sys/bus/pci/devices/0000:43:00.0/rom`

Now also able to execute at host :).

**Comment by QaidVoid** [comment]
yea. The command was supposed to be run as root.
I omitted it in the documentation because it seemed obvious.

I'll update the documentation since people might just put `sudo` before the command (which wouldn't work) instead of using `tee`.

**Comment by QaidVoid** [comment]
Updated documentation. :)
