### ISSUE TITLE
Cannot unbind efi-framebuffer

### ISSUE THREAD

**Issue by maskrtnik01** [QaidVoid/Complete-Single-GPU-Passthrough#24]
Hello,

I have started having issues with passtrough. Note that I had it setup, and it worked correctly. I was installing additional stuff to my system, when I noticed, it no longer works. I am using Ubuntu 22.10 host, Win 11 guest, nVidia GF RTX 3090 GPU.

I already did some troubleshooting, but I have hit dead end. I am entering following commands to ssh shell.

`virsh start <vm name>`
This command does not return. If I kill it, I can try to proceed, but it does not work.

`systemctl stop display-manager`
`echo 0 > /sys/class/vtconsole/vtcon0/bind`
These commands execute correctly.

`echo 0 > /sys/class/vtconsole/vtcon1/bind`
Here I get error, vtcon1 does not seem to exist on my system.

`echo efi-framebuffer.0 > /sys/bus/platform/drivers/efi-framebuffer/unbind`
This seems to be the cause. This does not execute correctly, it claims that efi framebuffer 0 does not exist.

`modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia`
I cannot unload drm, it is running and being used. Running remaining hook commands does not make a difference. Nor does trying to stop vm and go back to Ubuntu. Once I start the vm, the only thing I can do is reboot the system.

Last thing I remember installing when it stopped working was CUDA, and cockpit vm manager. I tried to uninstall both, but it does not make a difference.

Thanks in advance for any help,
Stanislav

**Comment by maskrtnik01** [comment]
Hello again,

I was able to solve these issues by reinstalling gpu drivers.

QaidVoid, do you have some area dedicated for a list of known solutions to problems? I believe this thread may be helpful to future users. Also, I have sent you mail last weekend, it is solved now, so no need to reply.

**Comment by QaidVoid** [comment]
Glad that you figured it out.

Someone had written troubleshooting guide which contains basic known issues and solutions, but is not updated to include new issues as they are encountered.
I'd make some lists for that when I get time..

Also, sorry for not reading your mail. I somehow completely missed the mail. I've been quite busy for a while..

**Comment by maskrtnik01** [comment]
No need to apologize. I understand, that you are running this repo in your free time.

I am not sure I figured it out completely. I fixed this single thing, but after re-entering Gnome, it was stuck in a crash-and-restart loop (maybe gnome, maybe x server,..). While trying to fix this, I pretty much messed my desktop environment, and had to totally strip my system to GUI-less linux and install gnome from scratch. Then, in login manager, I got way more entries to select desktop environment - so to be sure, I reinstalled the whole system.

I just hope, that I am not recommending a solution, that will lead more novice users to this mess. If you see some risk or reason, feel free to correct me.

Stanislav

**Comment by QaidVoid** [comment]
Reinstalling GPU drivers  should not cause any issue in most cases.

I'm not sure how you messed up your DE. If you find yourself having similar issues, I'd suggest to check the log files first which might help to figure out the issue. You could also reset the DE configuration to default by deleting its configuration files.
