### ISSUE TITLE
Libvirt gets stuck on Creating Domain.

### ISSUE THREAD

**Issue by Morphexe** [QaidVoid/Complete-Single-GPU-Passthrough#26]
Pretty much the title, after following the guide I get stuck on Creating Domain Loading bar forever.
Anything I might have missed?

**Comment by QaidVoid** [comment]
No idea why that's happening.
Are you trying to passthrough anything on initial setup? You should use normal configuration for initial setup if that's the case.
If not, use `dmesg` or `journalctl -xe` to find if there is any issue with libvirt.
