### ISSUE TITLE
hooks not working on gentoo (openrc)

### ISSUE THREAD

**Issue by drinkmonster** [QaidVoid/Complete-Single-GPU-Passthrough#28]
I edited the scripts to use rc-service to stop/start the display-manager service, but when I start the VM, nothing happens.

**Comment by QaidVoid** [comment]
Which DE/DM are you using?
If you're using Window Manager, you can instead try killing the WM process.

**Comment by drinkmonster** [comment]
the issue seemed to resolve itself lmao
