### ISSUE TITLE
For people that have permissions problems

### ISSUE THREAD

**Issue by moacirrf** [QaidVoid/Complete-Single-GPU-Passthrough#29]
Thanks for you job, works very well.
I'm a Manajro user, i had permission problems because some commands in **start.sh** and **stop.sh** needs to run as root.

So i need to run  my VM as root but the xml configuration of VM is on normal user folder.

So when i want to enter on win10 a run on terminal:

`
sudo virsh create /home/normal_user_name/.config/libvirt/qemu/win10.xml
`

thanks

**Comment by QaidVoid** [comment]
As long as you're in `libvirt` group, you should be able to run the VM as normal user even if the hooks have commands that require root access.

Can you run VM without libvirt hooks as normal user?

**Comment by moacirrf** [comment]
> As long as you're in `libvirt` and `input` group, you should be able to run the VM as normal user even if the hooks have commands that require root access.
> 
> Can you run VM without libvirt hooks as normal user?

My user is on input and libvirt groups.
I can run as normal user all other VMS that i don't configure hooks, but with hooks i can't start and i receive a blackscreen, so i type CRTL+ALT+F2 and i can login again on terminal.


But no problem, I just decided to share this information, so people don't give up, because it could be that small detail.
thanks
