### ISSUE TITLE
Start script for KDE/SDDM 

### ISSUE THREAD

**Issue by cih89** [QaidVoid/Complete-Single-GPU-Passthrough#31]
Just wanted to let you know that only stopping SDDM for KDE (Wayland) isn't enough. The start script would just freeze the output and not let the VM boot. It happens because just stopping SDDM doesn't kill the KDE session and you can't unload the GPU module.

For me it only works if I add this before systemctl stop display-manager:

`systemctl --user -M usernamehere@ stop plasma*
`

**Comment by QaidVoid** [comment]
Thanks.

**Comment by luka-nedeljkov** [comment]
Do I need to do this for the X11 session?

**Comment by QaidVoid** [comment]
iirc, you don't need to.

**Comment by luka-nedeljkov** [comment]
> iirc, you don't need to.

Tried it, works flawlessly, thanks for the doc file. It was a great resource to base my research on!

**Comment by AstroLightz** [comment]
Late reply, but is there a version of this I need to enter in the `stop.sh` script to start plasma wayland back?
