### ISSUE TITLE
Stuck on TianoCore splash screen

### ISSUE THREAD

**Issue by DumbledoreCalrissian** [QaidVoid/Complete-Single-GPU-Passthrough#37]
Hi.
I used your guide to setup gpu passthrough on my computer. I am using 
Arch Linux 
Kernel: 6.6.7-arch1-1 
GPU: AMD ATI Radeon RX 6800 XT

When start the vm, vm starts into the boot splash and gets stuck.

**Comment by QaidVoid** [comment]
Can you post your VM config?
