### ISSUE TITLE
PC sits at Vendor logo when starting VM

### ISSUE THREAD

**Issue by zJanny** [QaidVoid/Complete-Single-GPU-Passthrough#4]
When i start my VM, my PC just sits at the MSI BIOS logo

Log:
[win10.log](https://github.com/QaidVoid/Complete-Single-GPU-Passthrough/files/6155050/win10.log)

**Comment by zJanny** [comment]
Closed. I only added 2 of my 4 NVIDIA devices.

**Comment by Cubuss** [comment]
I have the same issue i only have 1 Nvidia device (3080) added both the GPU and NVIDIA audio hardware via the list,
