### ISSUE TITLE
black screen and no signal message on monitor.

### ISSUE THREAD

**Issue by SuperUser27** [QaidVoid/Complete-Single-GPU-Passthrough#47]
I Done everything what tutorial says.
I have amd gpu. (rx6700xt)
grub: 
GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 amd_iommu=on iommu=pt iommu=1 video=efifb:off disable_idle_d3=1"
I have iommu enabled in my bios. 
The /var/log/libvirt/qemu/win10.log is empty. 
The only thing I could done wrong is not installing the Virtio drivers in windows.
I could break it by remaking the vm again (like i deleted the vm machine and make it again. but it was after the black screen issue ) 
btw how can I make the vm to not taking thole monitor? Would be nice to just have it in one of my workspaces.

**Comment by SuperUser27** [comment]
nevermind

**Comment by Aizakkuno** [comment]
i'm using the same gpu -- is there something that fixed it for you?
