### ISSUE TITLE
Black screen "No more image in the PCI ROM"

### ISSUE THREAD

**Issue by camdenorrb** [QaidVoid/Complete-Single-GPU-Passthrough#7]
`lspci -v` Logs: https://gist.github.com/camdenorrb/b50de3ad0c0e9aded6367aa948db84e1

`dmesg` Logs: https://gist.github.com/camdenorrb/b65498dbe56f2425a95a8398ac3c2392

Qemu Log (I shutdown at the end, stalls on the audio part): https://gist.github.com/camdenorrb/e1ef0ba840ca0bdb69d7b9c5be02f0a6

Qemu config: https://gist.github.com/camdenorrb/ae83b456a1c75eff3dc4cf81913bf8bc

Any help is much appreciated :)

**Comment by franchioping** [comment]
You forgot the "rom file" section i think. I'm currently stuck in the same situation as you (black screen), but if i remember correctly there was a section to dumb ur gpu's vbios and add it to "virsh edit vmname".

If you figure it out PLEASE post it here, im stuck too!
